template-file-path: prod/templates/master.yaml
stack-name: prod-bem13-master-prod
region: us-east-1
capabilities:
  - CAPABILITY_IAM
  - CAPABILITY_NAMED_IAM
parameters:
  Environment: prod
  ProjectName: bem13
  TemplateBaseUrl: https://bem13-cloudformation-infra.s3.eu-west-1.amazonaws.com/prod/templates
  AppPort: 8080
  TestListenerPort: 9090
  DesiredCount: 2
  MinCapacity: 2
  MaxCapacity: 8
  CpuScaleOutThreshold: 70
  TaskCpu: 1024
  TaskMemory: 2048
  BlueTerminationWaitMinutes: 10
tags:
  Environment: prod
  Project: bem13-ecs-cicd
  ManagedBy: CloudFormation-GitSync
