template-file-path: test/templates/master.yaml
stack-name: test-bem13-master
region: us-east-1
capabilities:
  - CAPABILITY_IAM
  - CAPABILITY_NAMED_IAM
parameters:
  Environment: test
  ProjectName: bem13
  TemplateBaseUrl:  s3://bem13-cloudformation-infra/test/templates
  AppPort: 8080
  TestListenerPort: 9090
  DesiredCount: 1
  MinCapacity: 1
  MaxCapacity: 4
  CpuScaleOutThreshold: 70
  TaskCpu: 512
  TaskMemory: 1024
  BlueTerminationWaitMinutes: 5
tags:
  Environment: test
  Project: bem13-ecs-cicd
  ManagedBy: CloudFormation-GitSync
